version: "3"
services:
  app:
    container_name: frc-2641
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
      - "${BOLT_PORT}:3001"
    volumes:
      - .:/frc
      - /frc/node_modules
    links:
      - mongo
  mongo:
    container_name: frc-2641-mongo
    restart: always
    image: mongo:5
