<template>
	<section>
		<h4 class="text-h4">Gallery</h4>

		<hr class="mb-5" />

		<v-row>
			<v-col cols="12" md="4" v-for="photo in gallery">
				<Photo :photo="photo" />
			</v-col>
		</v-row>
	</section>
</template>

<script setup>
	let gallery = [
		{
			title: "The Alamo Before Dusk",
			author: "Aidan Liddy",
			date: "Saturday, November 4th, 2023 at 6:35 pm",
			src: "alamo",
			camera: "Canon EOS R",
			lens: "RF 24-240mm F4-6.3 IS USM",
			focalLength: "24 mm",
			speed: "1/640",
			aperture: "4.0",
			iso: "100",
			resolution: "2917 × 1823",
			fileSize: "3.8 MB",
			fileType: "JPEG",
			location: "The Alamo",
			city: "San Antonio, TX",
			map: "The%20Alamo",
		},
		{
			title: "Sruth in Aghaidh An Aird",
			author: "Aidan Liddy",
			date: "Thursday, July 27th, 2023 at 12:24 pm",
			src: "devils_chimney",
			camera: "DJI Mini 2",
			resolution: "3600 × 2250",
			fileSize: "6.6 MB",
			fileType: "JPEG",
			location: "The Devil's Chimney",
			city: "Glencar, Co. Leitrim, Ireland",
			map: "Devil's%20Chimney,Glencar,Leitrim,Ireland",
		},
		{
			title: "Sunset at Warrenpoint",
			author: "Aidan Liddy",
			date: "Sunday, July 23rd, 2023 at 5:06 pm",
			src: "warrenpoint",
			camera: "DJI Mini 2",
			resolution: "3518 × 2199",
			fileSize: "5 MB",
			fileType: "JPEG",
			location: "Warrenpoint",
			city: "Newry, Ireland",
			map: "Warrenpoint,Newry,Ireland",
		},
		{
			title: "Cucumber Falls",
			author: "Aidan Liddy",
			date: "Monday, Januray 8th, 2023 at 10:03 am",
			src: "cucumber_falls",
			camera: "Canon EOS R",
			lens: "RF 24-240mm F4-6.3 IS USM",
			focalLength: "24 mm",
			speed: "3/10",
			aperture: "14",
			iso: "200",
			resolution: "6238 × 3899",
			fileSize: "15.3 MB",
			fileType: "JPEG",
			location: "Ohiopyle State Park",
			city: "Ohiopyle, PA",
			map: "39.86303420102434,-79.50269118837431",
		},
		{
			title: "Remnants of the Troubles",
			author: "Aidan Liddy",
			date: "Thursday, July 28th, 2022 at 8:06 am",
			src: "n_ireland",
			camera: "Canon EOS R",
			lens: "EF-S 18-55mm F3.5-5.6 IS II",
			focalLength: "18 mm",
			speed: "1/1250",
			aperture: "3.5",
			iso: "100",
			resolution: "4047 × 2529",
			fileSize: "4.1 MB",
			fileType: "JPEG",
			location: "Border on the N1",
			city: "Dundalk, Co. Louth, Ireland",
			map: "54.1138319,-6.3698489",
		},
		{
			title: "Above Castle Roche",
			author: "Aidan Liddy",
			date: "Sunday, July 24th, 2022 at 9:34 am",
			src: "castle_roche",
			camera: "DJI Mini 2",
			resolution: "3600 × 2250",
			fileSize: "5.7 MB",
			fileType: "JPEG",
			location: "Castle Roche",
			city: "Dundalk, Co. Louth, Ireland",
			map: "Castle%20Roche,Dundalk,Louth,Ireland",
		},
		{
			title: "Sea Base at Dusk",
			author: "Aidan Liddy",
			date: "Thursday, June 16th, 2022 at 8:24 pm",
			src: "sea_base",
			camera: "Canon EOS R",
			lens: "EF-S 18-55mm F3.5-5.6 IS II",
			focalLength: "53 mm",
			speed: "1/250",
			aperture: "5.6",
			iso: "800",
			resolution: "4176 × 2610",
			fileSize: "8 MB",
			fileType: "JPEG",
			location: "Sea Base",
			city: "Islamorada, FL",
			map: "Florida+National+High+Adventure+Sea+Base,+Boy+Scouts+of+America",
		},
		{
			title: "The Tooth of Time",
			author: "Aidan Liddy",
			date: "Friday, August 6th, 2021 at 3:04 pm",
			src: "tooth_of_time",
			camera: "Apple iPhone X",
			lens: "Telephoto Camera",
			focalLength: "52 mm",
			speed: "1/2300",
			aperture: "2.4",
			iso: "16",
			resolution: "3358 × 2099",
			fileSize: "4.2 MB",
			fileType: "JPEG",
			location: "Philmont Scout Ranch",
			city: "Cimarron, NM",
			map: "36.4353033,-105.0034393",
		},
		{
			title: "Trail to Heck Meadow",
			author: "Aidan Liddy",
			date: "Wednesday, July 28th, 2021 at 10:39 am",
			src: "philmont",
			camera: "Apple iPhone X",
			lens: "Wide Camera",
			focalLength: "28 mm",
			speed: "1/2000",
			aperture: "1.8",
			iso: "20",
			resolution: "2232 × 1395",
			fileSize: "2.8 MB",
			fileType: "JPEG",
			location: "Philmont Scout Ranch",
			city: "Cimarron, NM",
			map: "36.4729487,-104.9880525",
		},
	];
</script>
